created common.css
mikaelelias/portfolio pull request #13
Opened 2023-09-22 23:52 UTC by mikaelelias

2023-09-25 09:49 UTC, isaaceliape commented on styles/about.css
Vc pode remove esse `import` já que ele já ta `common.css`.

2023-09-25 09:50 UTC, isaaceliape commented on styles/contact.css
Vc pode remove esse `import` já que ele já ta `common.css`.

2023-09-25 10:05 UTC, isaaceliape requested changes

2023-09-25 10:05 UTC, isaaceliape commented on contact.html
>      <title>Contact</title>
```suggestion
    <title>Mikael Elias - Contact</title>
```

2023-09-25 10:05 UTC, isaaceliape commented on about.html
>      <title>Mikael Elias</title>
To pensando agora, talvez seja bom colocar seu nome como prefixo no titulo de todas as páginas tipo assim:
```suggestion
    <title>Mikael Elias - About</title>
```

2023-09-25 10:05 UTC, isaaceliape commented on index.html
>      <title>Portfolio</title>
```suggestion
    <title>Mikael Elias - Home</title>
```

2023-09-25 10:05 UTC, isaaceliape commented on styles/common.css
> +.logo-wrap img {
Já que a gente já tá mexendo nesse css acho melhor já fazer umas melhorias.
Por exemplo é uma boa prática não referenciar as tags do HTML diretamente, nesse caso é melhor crias uma classe pra essa imagem no HTML e usar a classe aqui.

Ex:
```suggestion
.logo-wrap .logo-img {
```

2023-09-25 10:05 UTC, isaaceliape commented on styles/common.css
> +.navigation-header a {
Criar uma classe pra essa tag `<a>` tb.

Ex:
```suggestion
.navigation-header .navigation-link {
```

2023-09-25 10:05 UTC, isaaceliape commented on styles/common.css
> +    font-family: DM Sans;
Outra boa prática é colocar fonts alternativas caso a font principal não carrege por algum motivo.

Por exemplo, nesse caso se a font **DM Sans** não carregar ele vai tentar carregar a **Arial**, se a **Arial** não carregar e tenta a **Helvetica** e assim por diante.
```suggestion
    font-family: DM Sans, Arial, Helvetica, sans-serif;
```

2023-09-25 10:05 UTC, isaaceliape commented on styles/common.css
> +    font-family: DM Sans;
Adicionar fonts de "backup".
```suggestion
    font-family: DM Sans, Arial, Helvetica, sans-serif;
```

2023-09-25 10:05 UTC, isaaceliape commented on styles/common.css
> +    font-family: DM Sans;
Adicionar fonts de backup
```suggestion
    font-family: DM Sans, Arial, Helvetica, sans-serif;
```

2023-09-26 00:43 UTC, mikaelelias commented on styles/about.css
Feito!

2023-09-26 00:45 UTC, mikaelelias commented on styles/contact.css
Feito! Eu ia te perguntar isso quando fui criar o common.css, mas tu já estava dormindo.

2023-09-26 01:02 UTC, mikaelelias commented on contact.html
>      <title>Contact</title>
Feito!

2023-09-26 01:02 UTC, mikaelelias commented on about.html
>      <title>Mikael Elias</title>
Feito!

2023-09-26 01:03 UTC, mikaelelias commented on index.html
>      <title>Portfolio</title>
Feito!

2023-09-26 01:15 UTC, mikaelelias commented on styles/common.css
> +.logo-wrap img {
Feito!

2023-09-26 01:24 UTC, mikaelelias commented on styles/common.css
> +.navigation-header a {
Feito!

2023-09-26 01:38 UTC, mikaelelias commented on styles/common.css
> +    font-family: DM Sans;
A ideia é colocar fonte de backup em todos os css's né isso? Só pra alivio de conciencia...

2023-09-26 12:45 UTC, isaaceliape commented on styles/common.css
> +    font-family: DM Sans;
Isso, em todos os lugares que vc tá usando `font-family`

2023-09-27 00:43 UTC, mikaelelias commented on styles/common.css
> +    font-family: DM Sans;
Feito!

2023-09-27 00:43 UTC, mikaelelias commented on styles/common.css
> +    font-family: DM Sans;
Feito

2023-09-27 00:43 UTC, mikaelelias commented on styles/common.css
> +    font-family: DM Sans;
Feito

2023-09-27 00:43 UTC, merged